# Ruff configuration file
# See: https://docs.astral.sh/ruff/configuration/ for full options and explanations.

# Support Python 3.10+.
target-version = "py310"
# Set the maximum line length to 79.
line-length = 79

[lint]
# Add the `line-too-long` rule to the enforced rule set.
extend-select = ["E501"]